love.audio.setEffect("coolchorus", {type="chorus",volume=1,waveform="sine",phase=53.57,rate=2.5,depth=.02979,feedback=.9298,delay=.004081})
love.audio.setEffect("coolflanger", {type="flanger",volume=1,waveform="triangle",phase=0,rate=.27,depth=1,feedback=-.5,delay=.002})
love.audio.setEffect("coolequalizer", {type="equalizer",volume=1,lowgain=1,lowcut=200,lowmidgain=1,lowmidfrequency=500,lowmidbandwidth=1,highmidgain=1,highmidfrequency=3000,highmidbandwidth=1,highgain=1,highcut=6000})
love.audio.setEffect("coolcompressor", {type="compressor",volume=.63443077339102,enable=true})
love.audio.setEffect("coolreverb", {type="reverb",volume=1,density=1,diffusion=.3,gain=.3162,highgain=.7328,decaytime=1.49,decayhighratio=.86,earlygain=.25,earlydelay=.007,lategain=.9954,latedelay=.011,airabsorption=.9943,roomrolloff=0,highlimit=true})
mySource:setVolume(1)
mySource:setEffect("coolchorus")
mySource:setEffect("coolflanger")
mySource:setEffect("coolequalizer")
mySource:setEffect("coolcompressor")
mySource:setEffect("coolreverb")

mySource:setVolume(1)

love.audio.setEffect("coolchorus", {type="chorus",volume=1,waveform="sine",phase=53.57,rate=2.5,depth=.02979,feedback=.9298,delay=.004081})
love.audio.setEffect("coolflanger", {type="flanger",volume=1,waveform="triangle",phase=0,rate=.27,depth=1,feedback=-.5,delay=.002})
love.audio.setEffect("coolequalizer", {type="equalizer",volume=1,lowgain=1,lowcut=200,lowmidgain=1,lowmidfrequency=500,lowmidbandwidth=1,highmidgain=1,highmidfrequency=3000,highmidbandwidth=1,highgain=1,highcut=6000})
love.audio.setEffect("coolcompressor", {type="compressor",volume=.63443077339102,enable=true})
love.audio.setEffect("coolreverb", {type="reverb",volume=1,density=1,diffusion=.3,gain=.3162,highgain=.7328,decaytime=1.49,decayhighratio=.86,earlygain=.25,earlydelay=.007,lategain=.9954,latedelay=.011,airabsorption=.9943,roomrolloff=0,highlimit=true})
mySource:setVolume(1)
mySource:setEffect("coolchorus")
mySource:setEffect("coolflanger")
mySource:setEffect("coolequalizer")
mySource:setEffect("coolcompressor")
mySource:setEffect("coolreverb")